/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    AutoScroll: typeof import('./src/components/common/AutoScroll.vue')['default']
    InputContainer: typeof import('./src/components/InputContainer.vue')['default']
    InputSend: typeof import('./src/components/common/InputSend.vue')['default']
    MarkdownView: typeof import('./src/components/common/MarkdownView.vue')['default']
    ReceiveContainer: typeof import('./src/components/ReceiveContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendContainer: typeof import('./src/components/SendContainer.vue')['default']
    TitleOfHome: typeof import('./src/components/TitleOfHome.vue')['default']
    TransitionContainer: typeof import('./src/components/common/TransitionContainer.vue')['default']
  }
}
